### ISSUE TITLE
속성값을 유동적으로 변경

### ISSUE THREAD

**Issue by byunghyun** [nhn/tui.pagination#39]
![135b153](https://user-images.githubusercontent.com/6515175/117407729-eb4b8300-af49-11eb-866f-6ea7453ab797.png)

페이지네이션 만든다음에 저 속성값을 유동적으로 변경할 수 없을까요?!

**Comment by lja1018** [comment]
@byunghyun 
https://nhn.github.io/tui.pagination/latest/Pagination#setItemsPerPage
`setItemsPerPage` API를 사용해서 수정하시면 될 것 같습니다.

다음부턴 이슈를 영어로 올려주시면 감사하겠습니다.
